spring:
  application:
    name: eureka-server
server:
  port: 8000
eureka:
  instance:
    hostname: 101.132.156.185
  client:
    register-with-eureka: false
    fetch-registry: false
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/