demo:
  uri: lb://consumer
server:
  port: 8004
spring:
  application:
    name: gateway
  cloud:
    gateway:
      routes:
        - id: gateway
          uri: ${demo.uri} # uri以lb://开头（lb代表从注册中心获取服务），后面接的就是你需要转发到的服务名称
          predicates:
          - Path=/user/**

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8000/eureka/