spring:
  application:
    name: consumer
server:
  port: 8003

#feign:
#  client:
#    config:
#      default:
#        connectTimeout: 7000
#        readTimeout: 7000
#  hystrix:
#    enabled: true
#
#hystrix:
#  command:
#    default:
#      execution:
#        isolation:
#          thread:
#            timeoutInMilliseconds: 8000
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8000/eureka/